In [10]:
#Load the city name file
import pandas as pd
city = pd.read_excel("C:/Users/admin/OneDrive - BizViz Technologies Pvt Ltd/Desktop/Dump/city_name.xlsx")

city

   S.No       City
0     1     Mumbai
1     2    Kolkata
2     3    Chennai
3     4      Delhi
4     5       Pune
5     6     Jaipur
6     7      Jammu
7     8     Raipur
8     9      Patna
9    10  Bengaluru

In [8]:
list1 = []
import requests
import json
import pandas as pd
def weather(city):
    for c in city.City:
        city = str(c)
        url = "https://api.openweathermap.org/data/2.5/weather?"
        
        api_key = "668a5f49c34b15d1d2b99752b28683bf"
        com_url = url + "q=" + city + "&appid=" + api_key
        payload={}
        headers = {}
        response = requests.request("GET", com_url, headers=headers, data=payload)
        res =json.loads(response.text)
        list1.append(res)
    return[list1]

In [9]:
weather(city)

[[{'coord': {'lon': 72.8479, 'lat': 19.0144},
   'weather': [{'id': 711,
     'main': 'Smoke',
     'description': 'smoke',
     'icon': '50d'}],
   'base': 'stations',
   'main': {'temp': 303.14,
    'feels_like': 304.34,
    'temp_min': 302.09,
    'temp_max': 303.14,
    'pressure': 1009,
    'humidity': 51},
   'visibility': 4000,
   'wind': {'speed': 4.12, 'deg': 300},
   'clouds': {'all': 0},
   'dt': 1667215185,
   'sys': {'type': 1,
    'id': 9052,
    'country': 'IN',
    'sunrise': 1667178496,
    'sunset': 1667219762},
   'timezone': 19800,
   'id': 1275339,
   'name': 'Mumbai',
   'cod': 200},
  {'coord': {'lon': 88.3697, 'lat': 22.5697},
   'weather': [{'id': 721,
     'main': 'Haze',
     'description': 'haze',
     'icon': '50d'}],
   'base': 'stations',
   'main': {'temp': 303.12,
    'feels_like': 303.85,
    'temp_min': 303.12,
    'temp_max': 303.12,
    'pressure': 1009,
    'humidity': 48},
   'visibility': 5000,
   'wind': {'speed': 3.09, 'deg': 330},
   'clouds': {'all': 20},
   'dt': 1667215421,
   'sys': {'type': 1,
    'id': 9114,
    'country': 'IN',
    'sunrise': 1667175009,
    'sunset': 1667215799},
   'timezone': 19800,
   'id': 1275004,
   'name': 'Kolkata',
   'cod': 200},
  {'coord': {'lon': 80.2785, 'lat': 13.0878},
   'weather': [{'id': 701,
     'main': 'Mist',
     'description': 'mist',
     'icon': '50d'}],
   'base': 'stations',
   'main': {'temp': 299.14,
    'feels_like': 299.14,
    'temp_min': 299.14,
    'temp_max': 299.14,
    'pressure': 1008,
    'humidity': 89},
   'visibility': 3000,
   'wind': {'speed': 4.12, 'deg': 20},
   'clouds': {'all': 75},
   'dt': 1667215232,
   'sys': {'type': 1,
    'id': 9218,
    'country': 'IN',
    'sunrise': 1667176333,
    'sunset': 1667218359},
   'timezone': 19800,
   'id': 1264527,
   'name': 'Chennai',
   'cod': 200},
  {'coord': {'lon': 77.2167, 'lat': 28.6667},
   'weather': [{'id': 711,
     'main': 'Smoke',
     'description': 'smoke',
     'icon': '50d'}],
   'base': 'stations',
   'main': {'temp': 302.2,
    'feels_like': 301.72,
    'temp_min': 302.2,
    'temp_max': 302.2,
    'pressure': 1013,
    'humidity': 39},
   'visibility': 2500,
   'wind': {'speed': 0, 'deg': 0},
   'clouds': {'all': 0},
   'dt': 1667214908,
   'sys': {'type': 1,
    'id': 9165,
    'country': 'IN',
    'sunrise': 1667178128,
    'sunset': 1667218034},
   'timezone': 19800,
   'id': 1273294,
   'name': 'Delhi',
   'cod': 200},
  {'coord': {'lon': 73.8553, 'lat': 18.5196},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'base': 'stations',
   'main': {'temp': 300.65,
    'feels_like': 300.34,
    'temp_min': 300.65,
    'temp_max': 300.65,
    'pressure': 1011,
    'humidity': 39,
    'sea_level': 1011,
    'grnd_level': 950},
   'visibility': 10000,
   'wind': {'speed': 2.16, 'deg': 64, 'gust': 3.24},
   'clouds': {'all': 0},
   'dt': 1667215408,
   'sys': {'country': 'IN', 'sunrise': 1667178222, 'sunset': 1667219553},
   'timezone': 19800,
   'id': 1259229,
   'name': 'Pune',
   'cod': 200},
  {'coord': {'lon': 75.8167, 'lat': 26.9167},
   'weather': [{'id': 721,
     'main': 'Haze',
     'description': 'haze',
     'icon': '50d'}],
   'base': 'stations',
   'main': {'temp': 303.77,
    'feels_like': 302.5,
    'temp_min': 303.77,
    'temp_max': 303.77,
    'pressure': 1014,
    'humidity': 30},
   'visibility': 4000,
   'wind': {'speed': 2.06, 'deg': 80},
   'clouds': {'all': 0},
   'dt': 1667215213,
   'sys': {'type': 1,
    'id': 9170,
    'country': 'IN',
    'sunrise': 1667178333,
    'sunset': 1667218501},
   'timezone': 19800,
   'id': 1269515,
   'name': 'Jaipur',
   'cod': 200},
  {'coord': {'lon': 74.8667, 'lat': 32.7333},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'base': 'stations',
   'main': {'temp': 300.14,
    'feels_like': 299.68,
    'temp_min': 300.14,
    'temp_max': 300.14,
    'pressure': 1012,
    'humidity': 33,
    'sea_level': 1012,
    'grnd_level': 972},
   'visibility': 10000,
   'wind': {'speed': 0.69, 'deg': 274, 'gust': 0.96},
   'clouds': {'all': 10},
   'dt': 1667215351,
   'sys': {'type': 2,
    'id': 2075051,
    'country': 'IN',
    'sunrise': 1667179014,
    'sunset': 1667218275},
   'timezone': 19800,
   'id': 1269321,
   'name': 'Jammu',
   'cod': 200},
  {'coord': {'lon': 81.6333, 'lat': 21.2333},
   'weather': [{'id': 721,
     'main': 'Haze',
     'description': 'haze',
     'icon': '50d'}],
   'base': 'stations',
   'main': {'temp': 301.23,
    'feels_like': 301.78,
    'temp_min': 301.23,
    'temp_max': 301.23,
    'pressure': 1012,
    'humidity': 51},
   'visibility': 4000,
   'wind': {'speed': 2.57, 'deg': 30},
   'clouds': {'all': 98},
   'dt': 1667215292,
   'sys': {'type': 1,
    'id': 9168,
    'country': 'IN',
    'sunrise': 1667176535,
    'sunset': 1667217507},
   'timezone': 19800,
   'id': 1258980,
   'name': 'Raipur',
   'cod': 200},
  {'coord': {'lon': 85.1167, 'lat': 25.6},
   'weather': [{'id': 721,
     'main': 'Haze',
     'description': 'haze',
     'icon': '50d'}],
   'base': 'stations',
   'main': {'temp': 303.11,
    'feels_like': 304.3,
    'temp_min': 303.11,
    'temp_max': 303.11,
    'pressure': 1010,
    'humidity': 51},
   'visibility': 5000,
   'wind': {'speed': 0, 'deg': 0},
   'clouds': {'all': 20},
   'dt': 1667215458,
   'sys': {'type': 1,
    'id': 9129,
    'country': 'IN',
    'sunrise': 1667176004,
    'sunset': 1667216366},
   'timezone': 19800,
   'id': 1260086,
   'name': 'Patna',
   'cod': 200},
  {'coord': {'lon': 77.6033, 'lat': 12.9762},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'base': 'stations',
   'main': {'temp': 298.95,
    'feels_like': 299.07,
    'temp_min': 298.95,
    'temp_max': 299.05,
    'pressure': 1014,
    'humidity': 57},
   'visibility': 6000,
   'wind': {'speed': 4.12, 'deg': 40},
   'clouds': {'all': 40},
   'dt': 1667214812,
   'sys': {'type': 1,
    'id': 9205,
    'country': 'IN',
    'sunrise': 1667176968,
    'sunset': 1667219008},
   'timezone': 19800,
   'id': 1277333,
   'name': 'Bengaluru',
   'cod': 200}]]